name: Bug Report
description: "🐛 File a bug report"
title: "[Bug]: "
labels: ["bug", "needs-repro"]
assignees:
  - leon0399

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: input
    id: device-type
    attributes:
      label: Target Device
      description: What device you are building
      placeholder: x40 Haptic Suit, x16 Haptic Suit, etc.
    validations:
      required: true

  - type: textarea
    id: hardware-config
    attributes:
      label: Hardware Configuration
      description: Which components you are using?
      placeholder: ESP32-DevkitC-V4 or NodeMCU-32S, PCA9685 or not, etc.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Firmware Version
      description: What version of firmware are you running?
      placeholder: e.g. v0.1.0
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What OS or environment are you seeing the problem on?
      multiple: true
      options:
        - PCVR (Windows)
        - Meta Quest
        - iOS
        - Android
    validations:
      required: true

  - type: input
    id: bhaptics-verions
    attributes:
      label: bHaptics Player Version
      description: What version on bHaptics Player are you running?
      placeholder: e.g. 1.8.2.1
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
    validations:
      required: false

  - type: textarea
    id: serial-logs
    attributes:
      label: Serial output
      description: Please copy and paste serial output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
    validations:
      required: false

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: e.g. discord#0123, @username
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
