blank_issues_enabled: true

contact_links:
  - name: 📖 SenseShift Documentation
    url: https://senseshift.github.io/
    about: Documentation on installing and using SenseShift Firmware
  - name: 🕹 SenseShift on Discord
    url: https://discord.gg/YUtRKAqty2
    about: Join the Discord server for support and discussion.
