name: Check bHaptics builds

on:
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - '**/*.md'
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'

jobs:
  check-build-os:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        target:
          - bhaptics_tactsuit_x40

        # Enabling all flags to test build for every feature
        battery_flag:
          - BATTERY_ENABLED=true
        serial_plotter_flag:
          - SERIAL_PLOTTER=true

    # C'mon, GitHub, give us YAML anchors, it's a basic feature! cc actions/runner#1182
    steps:
      - uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-pio-${{ hashFiles('**/lockfiles') }}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Update build flags (non-macOS)
        if: runner.os != 'macOS'
        run: |
          sed -i '/__OH_FIRMWARE__/p; s/__OH_FIRMWARE__/${{ matrix.battery_flag }}/' platformio.ini
          sed -i '/__OH_FIRMWARE__/p; s/__OH_FIRMWARE__/${{ matrix.serial_plotter_flag }}/' platformio.ini

      - name: Update build flags (macOS)
        if: runner.os == 'macOS'
        run: |
          sed -i '' '/__OH_FIRMWARE__/p; s/__OH_FIRMWARE__/${{ matrix.battery_flag }}/' platformio.ini
          sed -i '' '/__OH_FIRMWARE__/p; s/__OH_FIRMWARE__/${{ matrix.serial_plotter_flag }}/' platformio.ini

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          pio upgrade --dev
          pio pkg update --global

      - name: Build
        run: |
          echo "::group::platformio.ini"
          cat platformio.ini
          echo "::endgroup::"
          pio run --environment ${{matrix.target}}

  build-flags:
    needs: check-build-os
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target:
          # Using x40 as it is uses both ledc and pca9685 outputs
          - bhaptics_tactsuit_x40
        battery_flag:
          - BATTERY_ENABLED=true
          - BATTERY_ENABLED=false
        serial_plotter_flag:
          - SERIAL_PLOTTER=false
          - SERIAL_PLOTTER=true

    steps:
      - uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-pio-${{ hashFiles('**/lockfiles') }}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Update build flags (non-macOS)
        if: runner.os != 'macOS'
        run: |
          sed -i '/__OH_FIRMWARE__/p; s/__OH_FIRMWARE__/${{ matrix.battery_flag }}/' platformio.ini
          sed -i '/__OH_FIRMWARE__/p; s/__OH_FIRMWARE__/${{ matrix.serial_plotter_flag }}/' platformio.ini

      - name: Update build flags (macOS)
        if: runner.os == 'macOS'
        run: |
          sed -i '' '/__OH_FIRMWARE__/p; s/__OH_FIRMWARE__/${{ matrix.battery_flag }}/' platformio.ini
          sed -i '' '/__OH_FIRMWARE__/p; s/__OH_FIRMWARE__/${{ matrix.serial_plotter_flag }}/' platformio.ini

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          pio upgrade --dev
          pio pkg update --global

      - name: Build
        run: |
          echo "::group::platformio.ini"
          cat platformio.ini
          echo "::endgroup::"
          pio run --environment ${{matrix.target}}

  build-targets:
    needs: build-flags
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - bhaptics_tactsuit_x16
          - bhaptics_tactsuit_x16_pca9685
          - bhaptics_tactsuit_x40
          - bhaptics_tactosy2_forearm_right
          - bhaptics_tactosyh_hand_right
          - bhaptics_tactosyf_foot_right
          - bhaptics_tactal

        # Enabling all flags to test build for every feature
        battery_flag:
          - BATTERY_ENABLED=true
        serial_plotter_flag:
          - SERIAL_PLOTTER=true

    steps:
      - uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-pio-${{ hashFiles('**/lockfiles') }}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Update build flags (non-macOS)
        if: runner.os != 'macOS'
        run: |
          sed -i '/__OH_FIRMWARE__/p; s/__OH_FIRMWARE__/${{ matrix.battery_flag }}/' platformio.ini
          sed -i '/__OH_FIRMWARE__/p; s/__OH_FIRMWARE__/${{ matrix.serial_plotter_flag }}/' platformio.ini

      - name: Update build flags (macOS)
        if: runner.os == 'macOS'
        run: |
          sed -i '' '/__OH_FIRMWARE__/p; s/__OH_FIRMWARE__/${{ matrix.battery_flag }}/' platformio.ini
          sed -i '' '/__OH_FIRMWARE__/p; s/__OH_FIRMWARE__/${{ matrix.serial_plotter_flag }}/' platformio.ini

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          pio upgrade --dev
          pio pkg update --global

      - name: Build
        run: |
          echo "::group::platformio.ini"
          cat platformio.ini
          echo "::endgroup::"
          pio run --environment ${{matrix.target}}
