name: PlatformIO CI

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - docs/**
      - '**/*.md'
  push:
    branches:
      - master
    paths-ignore:
      - docs/**
      - '**/*.md'

jobs:
  build:
    if: github.repository == 'openhaptics/openhaptics-firmware'

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        target:
          - bhaptics_tactsuit_x16
          - bhaptics_tactsuit_x16_pca9685
          - bhaptics_tactsuit_x40

    steps:
    - uses: actions/checkout@v3

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-pio-${{ hashFiles('**/lockfiles') }}
        restore-keys: |
          ${{ runner.os }}-pio-

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        pio upgrade --dev
        pio pkg update --global

    - name: Build
      run: |
        pio run --environment ${{matrix.target}}
